# Generated by Django 5.1.7 on 2025-03-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=60)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('foto', models.ImageField(blank=True, height_field='imagen_altura', null=True, upload_to='images/', width_field='imagen_anchura')),
                ('imagen_altura', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen_anchura', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
