# Generated by Django 5.1.7 on 2025-04-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_cordenadas_alter_platillo_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('foto', models.ImageField(blank=True, height_field='imagen_altura', null=True, upload_to='images/', width_field='imagen_anchura')),
                ('imagen_altura', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen_anchura', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='administrador',
        ),
        migrations.DeleteModel(
            name='Platillo',
        ),
    ]
